// Sample data for the NFL betting analysis dashboard
// In production, this would be replaced by data from fetch_nflfastr_data.py

export const analysisData = {
  generatedAt: "2025-01-13T12:00:00.000Z",
  season: 2024,
  modelMetrics: {
    r2_score: 0.8472,
    mae: 3.21,
    rmse: 4.15,
    training_samples: 272,
  },
  summaryStats: {
    gamesAnalyzed: 4,
    avgEdge: 2.1,
    overPicks: 2,
    underPicks: 1,
    holdPicks: 1,
    avgModelTotal: 51.1,
    avgVegasTotal: 49.9,
  },
  games: [
    {
      homeTeam: "Chiefs",
      awayTeam: "Texans",
      homeAbbr: "KC",
      awayAbbr: "HOU",
      gameDate: "Sat, Jan 18",
      gameTime: "4:30 PM ET",
      vegasTotal: 48.5,
      modelTotal: 51.2,
      homeScore: 27.8,
      awayScore: 23.4,
      edge: 2.7,
      recommendation: "over" as const,
      homeOffEpa: 0.142,
      homeDefEpa: -0.087,
      awayOffEpa: 0.024,
      awayDefEpa: 0.032,
    },
    {
      homeTeam: "Eagles",
      awayTeam: "Rams",
      homeAbbr: "PHI",
      awayAbbr: "LAR",
      gameDate: "Sun, Jan 19",
      gameTime: "3:00 PM ET",
      vegasTotal: 44.0,
      modelTotal: 42.1,
      homeScore: 24.2,
      awayScore: 17.9,
      edge: -1.9,
      recommendation: "hold" as const,
      homeOffEpa: 0.098,
      homeDefEpa: -0.112,
      awayOffEpa: 0.067,
      awayDefEpa: 0.045,
    },
    {
      homeTeam: "Bills",
      awayTeam: "Ravens",
      homeAbbr: "BUF",
      awayAbbr: "BAL",
      gameDate: "Sun, Jan 19",
      gameTime: "6:30 PM ET",
      vegasTotal: 51.5,
      modelTotal: 52.8,
      homeScore: 28.1,
      awayScore: 24.7,
      edge: 1.3,
      recommendation: "hold" as const,
      homeOffEpa: 0.156,
      homeDefEpa: -0.078,
      awayOffEpa: 0.189,
      awayDefEpa: -0.024,
    },
    {
      homeTeam: "Lions",
      awayTeam: "Commanders",
      homeAbbr: "DET",
      awayAbbr: "WAS",
      gameDate: "Sat, Jan 18",
      gameTime: "8:00 PM ET",
      vegasTotal: 55.5,
      modelTotal: 58.3,
      homeScore: 31.4,
      awayScore: 26.9,
      edge: 2.8,
      recommendation: "over" as const,
      homeOffEpa: 0.178,
      homeDefEpa: -0.045,
      awayOffEpa: 0.112,
      awayDefEpa: 0.067,
    },
  ],
}
